project:
  type: website
  output-dir: "docs"
date: today
lang: fr
language:
  title-block-author-single: "Auteur"
author:
  - name: "D<sup>r</sup> Philippe MICHEL"
    orcid: "0000-0003-2392-7186"
    email: "philippe.michel@ght-novo.fr"
    role: "Statisticien"
    affiliations:
        name: "USRC - Hôpital NOVO"
        city: Pontoise
        department: "Unité de Soutien à la Recherche Clinique"
website:
  image: novo_usrc.png
  title: "Suivi Pharma"
  back-to-top-navigation: true
  reader-mode: true
  search:
    location: sidebar
    type: textbox
  navbar:
    logo: novo_usrc.png
    background: primary
    search: true
    right:
       - icon: github
         href: https://github.com/philippemichel
       - icon: mailbox
         text: mail
         href: mailto:philippe.michel@ght-novo.fr
  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents: auto
  open-graph:
    locale: fr_FR
format:
    html:
      code-fold: true
      page-layout: full
      highlight-style: ayu
      theme:
        light:
          - sandstone
          - custom.scss
        dark: cyborg
      fontsize: 1.2em
toc: true
warning: false
message: false
